### ISSUE TITLE
Collapsing "And" nesting optimization, configurable?

### ISSUE THREAD

**Issue by egberts** [egberts/pyparsing#1]
@pyparsing/@ptmcg,

About 237 ParserElements variables later, I've come to a stop here while working on the ISC Bind v9 configuration file syntax parser.  Spent 2 weeks on this lone issue alone.  

Did a full ParserElement reconstruct from the top-down; and a full reconstruct from the bottom-up:  No dice.

I've enclosed a tidy standalone unit test (but not UnitTest) file for Python 3.7 that would fully exercise the entire shebang until it would fail at the last two sub tests.

I'm pretty sure it's something innocuous and am eager to push this out to open source.

The two bugs are listed at this link.  That file is also a self-contained pyparsing executable unit test, that I specially condensed to a bare minimum for your convenience and debugging ease.

I'm anxious to know where I went wrong.  Meanwhile, i'm still debugging pyparsing on this.

https://github.com/egberts/pyparsing/blob/0d8ee81133497603de55145eb0c5791f85a7f421/test/test_isc_bind_aml.py#L561

**Comment by ptmcg** [comment]
I think there are a couple of things going on here, and one may be a bug with attaching results names to Forwards. As a workaround change this line:

    )('aml_nesting')

to

    ).setName('aml_nesting')

In my experience, Forwards are more suited to structuring in Groups than naming with results names.

I would also suggest not using ZeroOrMore structures as an alternative, since they force repetition of just one type. Also they can "match" nothing when you really wanted the other expression.  

That is, instead of:
    
    A = ZeroOrMore(Word(nums))
    B = Forward()
    B <<= '{' + (A | Group(B)) + '}'
    
    B.runTests("""
    { 1 2 3 { 4 5 {}} }
    {}
    """)

which gives
    
    { 1 2 3 { 4 5 {}} }
            ^
    FAIL: Expected "}", found '{'  (at char 8), (line:1, col:9)

    {}
    []


Move the ZeroOrMore higher up in the parser:
    
    A = Word(nums)
    B = Forward()
    B <<= '{' + ZeroOrMore(A | Group(B)) + '}'
    
    B.runTests("""
    { 1 2 3 { 4 5 {}} }
    {}
    """, fullDump=False)

Giving:
    
    { 1 2 3 { 4 5 {}} }
    ['1', '2', '3', ['4', '5', []]]
    {}
    []

I'll continue to look at the Forward results name issue.

**Comment by egberts** [comment]
Well, that was unexpected...

    UserWarning: warn_multiple_tokens_in_named_alternation: setting 
    results name 'aml_nesting' on MatchFirst expression may only 
    return a single token for an And alternative, in future will return 
    the full list of tokens
      )('aml_nesting')  # ('addr_choices_forward*') 

I guess I am that future, @ptmcg.  How do I get the full list of tokens?

**Comment by ptmcg** [comment]
What version of pyparsing are you using? If 2.4.x, then getting the full list is the default behavior, and I should probably have taken out this warning. (This was the big compatibility problem in 2.3, where I fixed a bug, but ended up breaking code that relied on the buggy behavior.) Solution is to Group the expression being named. More details on the wiki page on debugging and troubleshooting, and in the CHANGES file that discusses these flags and the corresponding `__compat__` switch.

**Comment by ptmcg** [comment]
My testing is also not seeing any problem with combining results naming with `<<=`:

    a <<= (b | '(' + a + ')')('a_name')

I think your basic expressions are all good, it is just the combining into repetitions and recursions that need a little help (I already hear you saying, "is that all?").

**Comment by egberts** [comment]
Using your master branch since your August 5th (or there-around) git commit:  2.5.0a1.

**Comment by ptmcg** [comment]
From your examples, I came up with this BNF:

    addr ::= name or IP address
    acl_item ::= ['!'] ( acl_addr ';'  
                         | '{' [acl_item] '}' ';')...
    acl ::= 'acl' name '{' [acl_item]... '}' ';'

I used your defined terminals to convert to a Pyparsing expression for a standalone ACL:

    acl_item = Forward()
    acl_addr = addr('addr*')
    # I think the FollowedBy is important, to prevent accepting a lone '!' with no addrs or subitems
    acl_item <<= Group(Optional(exclamation('not') + FollowedBy(acl_item))
                       + Group(OneOrMore(acl_addr + semicolon |
                                         (lbrack - Optional(acl_item) + rbrack + semicolon)
                                         )
                               ))('items')
    
    clause_stmt_acl_standalone = (
        (
                Literal('acl').suppress()
                # + Word(alphanums + '_-')('acl_name')
                + Word(alphas, alphanums + '_-').setName('acl_name')('acl_name')
                + lbrack
                + ZeroOrMore(acl_item)('aml_series')
                + rbrack
                + semicolon
        )
    )

I didn't find it useful to define a separate "this is the first level which is not allowed to have a 'not' operator", I just lumped it into the definition of the standalone acl.

Your tests were a bit verbose for me, so I did subset of them using runTests:

    clause_stmt_acl_standalone.runTests("""
        acl null {};
        acl nested_aml { ! { name_5015; name_5016; }; };
        acl nested_aml { ! name_5015; name_5016; };
        acl simplest_statement { ! simple_statement_w_exclamation; };
        acl a { b; };  
        acl c { d; e; f; }; 
        acl g { ! h; ! { i; }; };
    """)

I tried adding and removing grouping and results names with varying results, you should experiment to see what makes the most sense in navigating the parsed bits from these ACL declarations.

**Comment by egberts** [comment]
Fixed it!!!  Now coasting to a completion.  Thank you, @ptmcg.

**Comment by egberts** [comment]
Updated here.  https://github.com/egberts/pyparsing/blob/master/test/test_isc_bind_aml.py

**Comment by ptmcg** [comment]
While working on this, I saw that `ZeroOrMore(expr)('name')` does not generate an empty list under the results name "name" in the event no `expr`s are parsed. This will be fixed in the next release (which after discussing with others will not be 2.5.0, but 3.0.0, to better reflect pyparsing is no longer supporting Py2).

I saw you still have the "Bug?" comments in your code, are they still an issue?

**Comment by egberts** [comment]
Ooops.   Those two bugs are gone; will update in next release

**Comment by egberts** [comment]
I managed to create an empty list by wrapping it with a `Group()` around the ZeroOrMore.
